# Chapter 0: Pytorch and Deep Learning Fundamentals

structured data: traditional ML(e.g. XGBoost)
deep learning: unstructured data (e.g. neural network)

## Neural Network
we have inputs(images, voices, and words), and do numerical encoding(we incode the inputs as matrix). Then choose the appropriate neural network for the problem, that is to learn representation(patterns/features/weights). So that we can get numerical representation outputs(also matrix). Finally get the human understandable outputs.

# PyTorch - Tensor!

In [1]:
from importlib import import_module

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sympy.stats.sampling.sample_numpy import numpy
from torch.fft import Tensor

In [2]:
# version
torch.__version__

'2.5.0+cu121'

## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
Matrix = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
Matrix

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([3, 2])

In [ ]:
# Tensor
TENSOR = torch.Tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[9,8,7],
                        [6,5,4],
                        [3,2,1]]])
TENSOR

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[9., 8., 7.],
         [6., 5., 4.],
         [3., 2., 1.]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])

### Random tensors

Why random tensors?

Important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data-> update random numbers`

In [ ]:
# Create a random tensors of size(3,4)
random_tensor = torch.rand(3,3,3)
random_tensor

tensor([[[0.2380, 0.1111, 0.3919],
         [0.5536, 0.0226, 0.7085],
         [0.3668, 0.8275, 0.8452]],

        [[0.8176, 0.4765, 0.4623],
         [0.0674, 0.3542, 0.8603],
         [0.6735, 0.0159, 0.7034]],

        [[0.2972, 0.0412, 0.4791],
         [0.2350, 0.2399, 0.1777],
         [0.0325, 0.5358, 0.0489]]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) # height, width,colour channels (R,G,B)
random_image_tensor.shape, random_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,3,4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,3,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range and get deprecated message, use torch.arrange
one_to_ten = torch.arange(0,11,1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,# what datatype is the tensor (e.g. float32 or float16 )
                               device=None,# What device is your tensors on
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
mul = float_16_tensor * int_32_tensor
mul.dtype

torch.float16

### Getting information from tensors
1. Tensors not right datatype - to get datatype from a tensor, `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7226, 0.2664, 0.3782, 0.8478],
        [0.9408, 0.9261, 0.3493, 0.8799],
        [0.5692, 0.8266, 0.9772, 0.4500]])

In [ ]:
# Find out details about the tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on:{some_tensor.device}')


tensor([[0.7226, 0.2664, 0.3782, 0.8478],
        [0.9408, 0.9261, 0.3493, 0.8799],
        [0.5692, 0.8266, 0.9772, 0.4500]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Mul by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (**dot product**)


There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimension** must match (矩阵乘法法则）

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.7094, 0.8788, 1.0695],
        [0.6721, 0.6508, 0.7817],
        [0.6833, 0.7055, 0.8506]])

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.matmul(tensor_A,tensor_B.T).shape


torch.Size([3, 3])

### Finding the min, max, mean, sum (tensor aggregation)

In [ ]:
x= torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
# the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
# Find the position
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x[0],x[9]

(tensor(0), tensor(90))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a define shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way



In [ ]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Change the view
z = x.view(1,10)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original ones
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked_dim0 = torch.stack([x,x,x,x], dim=0)
x_stacked_dim1 = torch.stack([x,x,x,x],dim=1)
x_stacked_dim0,x_stacked_dim1

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]))

In [ ]:
x_squeeze = x_reshape.squeeze()

In [ ]:
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
x_unsqueeze

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]
x_permuted = x_original.permute(2,0,1) # [color_channels, height, width]
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# Get all values of oth and 1st dimensions but only index 1 of 2nd deminsion
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[:,2,2])

# Index on x to return 3,6,9
print(x[:,:,2])

tensor([9])
tensor([[3, 6, 9]])


In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

### PyTorch tensors & Numpy

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Nmpy -> `torch.Tensor.numpy()`

PyTorch reflects numpy's default datatype of float64 unless specified otherwise

In [ ]:
# Nmpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproduceility (trying to take random out of random)

**In short, how a neural network learns:**

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2460, 0.6912, 0.6333, 0.8919],
        [0.4169, 0.4175, 0.1030, 0.2778],
        [0.9591, 0.3329, 0.8924, 0.8304]])
tensor([[0.1377, 0.0021, 0.2686, 0.5654],
        [0.9372, 0.0967, 0.9814, 0.7508],
        [0.2319, 0.6646, 0.6981, 0.0296]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPIs (and making faster computations)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + pyTorch working behind the screnes to make everything hunky dory(good).

## 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - takes a litle bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

## 2. Check or GPU acccess with PyTorch

In [3]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on GPU

The reason is because using a GPU results in faster computations.

In [7]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, cannot transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
# To fix the issue, we can firest set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')